Census data
https://www.census.gov/data/developers/data-sets/acs-1year.html

Using Census data from ACS 1-Year Detailed Tables 
https://api.census.gov/data/2016/acs/acs1/variables.html 
https://api.census.gov/data/2016/acs/acs1/examples.html 

BY stateâ€º congressional district api calls: 
https://api.census.gov/data/2016/acs/acs1?get=B01001_001E,NAME&for=congressional%20district:*&key=YOUR_KEY_GOES_HERE
https://api.census.gov/data/2016/acs/acs1?get=B01001_001E,NAME&for=congressional%20district:01&in=state:01&key=YOUR_KEY_GOES_HERE

In [3]:
# Import dependices
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
from api_keys import api_key

In [4]:
# Create a call for the Census using our api_key

base_url = "https://api.census.gov/data/2016/acs/acs1?get="
variables = 'B01001_001E,B01002_001E,B01002_002E,B01002_003E'
district_base = "&for=congressional%20district:"
district = '*'
key = '&key='+api_key
url = base_url+variables+district_base+district+key
#print(url)

In [5]:
# Create a function to return Pandas Data Frames from our pull requests

def getAPIData(pd_url):
    response = requests.get(pd_url)
    res = response.json()
    url_df = pd.DataFrame(res)
    return url_df

In [6]:
# Try our function out to see if it works
# Get population data per state per distract from the Census

raw_dist_pop_df = getAPIData(url)
#raw_dist_pop_df.head()

# Change column names
raw_dist_pop_df.columns=['Population','Mean Age','Mean Age Male','Mean Age Female','State','Congressional Distract']
#raw_dist_pop_df.head()

# Drop first row
dist_pop_df = raw_dist_pop_df.drop(raw_dist_pop_df.index[0])
dist_pop_df.head()

,Population,Mean Age,Mean Age Male,Mean Age Female,State,Congressional Distract
1,704457,39.6,38.3,41.0,01,01
2,681621,38.2,36.7,40.1,01,02
3,709482,38.3,36.6,39.8,01,03
4,683273,40.7,39.7,42.0,01,04
5,712529,40.1,38.4,41.8,01,05

In [8]:
# We can create new DataFrame to find population per state
dist_pop_df

,Population,Mean Age,Mean Age Male,Mean Age Female,State,Congressional Distract
1,704457,39.6,38.3,41.0,01,01
2,681621,38.2,36.7,40.1,01,02
3,709482,38.3,36.6,39.8,01,03
4,683273,40.7,39.7,42.0,01,04
5,712529,40.1,38.4,41.8,01,05
6,706308,39.0,37.8,40.2,01,06
7,665630,36.5,34.2,38.3,01,07
8,741894,33.5,32.8,34.3,02,00
9,766924,37.5,36.6,38.4,04,01
10,722770,40.8,39.0,43.0,04,02
11,752284,32.7,31.0,34.2,04,03
12,753807,47.9,45.7,50.0,04,04
13,785110,37.5,36.6,38.4,04,05
14,764776,42.3,40.5,44.4,04,06
15,818387,29.7,29.7,29.7,04,07
16,782511,42.6,40.8,44.1,04,08
17,784502,33.5,32.4,34.6,04,09
18,725733,39.9,38.0,41.9,05,01
19,758929,36.9,35.9,37.9,05,02
20,794237,35.3,34.5,36.4,05,03
21,709349,40.8,38.9,42.2,05,04
22,703162,43.0,40.9,45.1,06,01
23,716202,44.1,42.8,45.3,06,02
24,740253,35.0,34.2,36.0,06,03
25,737169,44.2,42.5,45.9,06,04
26,735968,40.4,38.8,42.4,06,05
27,763987,33.9,32.7,35.0,06,06
28,738468,38.5,37.2,40.0,06,07
29,723600,34.5,32.9,35.6,06,08
30,760794,35.1,34.1,35.9,06,09
...,...,...,...,...,...,...
408,735178,42.7,41.1,44.2,51,05
409,754859,40.3,39.2,41.5,51,06
410,775369,39.9,39.0,40.9,51,07
411,783079,36.1,35.7,36.4,51,08
412,707012,43.0,40.9,44.7,51,09
413,827279,37.9,36.7,38.7,51,10
414,802910,36.9,36.2,37.5,51,11
415,738149,38.5,37.5,39.5,53,01
416,728550,38.2,37.2,39.4,53,02
417,722277,39.8,38.9,40.6,53,03
418,715254,34.0,33.2,34.7,53,04
419,708228,37.4,36.1,38.9,53,05
420,699178,41.6,39.7,43.9,53,06
421,766221,36.6,36.2,37.2,53,07
422,738218,38.0,37.6,38.3,53,08
423,739873,37.3,36.4,38.3,53,09
424,732052,36.1,34.5,37.9,53,10
425,617131,41.4,40.0,42.8,54,01
426,622850,42.6,41.7,43.4,54,02
427,591121,42.9,41.6,43.9,54,03
428,715327,40.8,39.1,42.2,55,01
429,757511,36.6,35.5,37.8,55,02
430,721847,38.4,37.6,39.3,55,03
431,713297,32.8,31.4,34.1,55,04
432,722739,41.4,40.1,43.0,55,05
433,711318,41.8,40.5,43.4,55,06
434,708541,44.6,43.6,45.6,55,07
435,728129,40.5,39.5,41.6,55,08
436,585501,37.2,36.6,37.8,56,00
437,3411307,40.7,38.8,42.5,72,98